# Generated by Django 3.1.3 on 2020-11-22 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('busType', models.CharField(max_length=50)),
                ('seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('rID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('jDate', models.DateField()),
                ('jTime', models.TimeField()),
                ('bID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteview.bus')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableBusRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jDate', models.DateField()),
                ('jTime', models.TimeField()),
                ('bID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteview.bus')),
                ('rID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteview.route')),
            ],
        ),
    ]
