# Generated by Django 3.1.3 on 2020-11-22 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='bID',
        ),
        migrations.RemoveField(
            model_name='route',
            name='jDate',
        ),
        migrations.RemoveField(
            model_name='route',
            name='jTime',
        ),
        migrations.CreateModel(
            name='AvailableBusRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jDate', models.DateField()),
                ('jTime', models.TimeField()),
                ('bID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteview.bus')),
                ('rID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteview.route')),
            ],
        ),
    ]
