# Generated by Django 3.1.3 on 2020-11-22 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('siteview', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='route',
        #     name='bID',
        # ),
        # migrations.RemoveField(
        #     model_name='route',
        #     name='jDate',
        # ),
        # migrations.RemoveField(
        #     model_name='route',
        #     name='jTime',
        # ),
        migrations.AddField(
            model_name='bus',
            name='costpseat',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='BookedTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked', models.IntegerField()),
                ('amount', models.IntegerField(null=True)),
                ('bID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteview.bus')),
                ('rID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteview.route')),
                ('uID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        # migrations.CreateModel(
        #     name='AvailableBusRoute',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('jDate', models.DateField()),
        #         ('jTime', models.TimeField()),
        #         ('bID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteview.bus')),
        #         ('rID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteview.route')),
        #     ],
        # ),
    ]
