# Generated by Django 3.1.3 on 2020-12-03 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteview', '0002_auto_20201123_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedticket',
            name='id',
        ),
        # migrations.RemoveField(
        #     model_name='bus',
        #     name='costpseat',
        # ),
        # migrations.RemoveField(
        #     model_name='route',
        #     name='bID',
        # ),
        # migrations.RemoveField(
        #     model_name='route',
        #     name='jDate',
        # ),
        # migrations.RemoveField(
        #     model_name='route',
        #     name='jTime',
        # ),
        migrations.AddField(
            model_name='bookedticket',
            name='tID',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        # migrations.CreateModel(
        #     name='AvailableBusRoute',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('jDate', models.DateField()),
        #         ('jTime', models.TimeField()),
        #         ('bID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteview.bus')),
        #         ('rID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteview.route')),
        #     ],
        # ),
    ]
