# Generated by Django 3.1.3 on 2020-12-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteview', '0005_auto_20201204_1539'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='bus',
        #     name='seats',
        # ),
        # migrations.RemoveField(
        #     model_name='route',
        #     name='bID',
        # ),
        # migrations.RemoveField(
        #     model_name='route',
        #     name='jDate',
        # ),
        # migrations.RemoveField(
        #     model_name='route',
        #     name='jTime',
        # ),
        migrations.AddField(
            model_name='availablebusroute',
            name='seats',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookedticket',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
